# Generated by Django 5.0.4 on 2024-05-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_purchaseorder_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancerecord',
            name='deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='deleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
