# Generated by Django 5.0.4 on 2024-05-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_performancerecord_deleted_purchaseorder_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='average_response_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
