# Generated by Django 5.0.4 on 2024-05-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_vendor_average_response_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancerecord',
            name='average_response_time',
            field=models.FloatField(null=True),
        ),
    ]
