# Generated by Django 5.0.4 on 2024-05-12 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_performancerecord_average_response_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='delivered_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
