# Generated by Django 5.0.4 on 2024-05-12 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_purchaseorder_delivered_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='any_issue',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
