# Generated by Django 5.0.4 on 2024-05-12 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_purchaseorder_acknowledgment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancerecord',
            name='average_response_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='average_response_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
